/**
 * seed.ts — 30 example components across every system.
 *
 * Figures are realistic but approximate. Confirm against the real datasheet
 * and your van's payload sticker before buying or building. This file is the
 * shape an AI agent should produce when populating from manufacturer data:
 * fill every field you can verify, cite a source, set confidence honestly.
 */
import type { VanComponent } from "./types";

export const SEED_COMPONENTS: VanComponent[] = [
  // ---------------- ELECTRICAL ----------------
  {
    id: "el-bb-100", name: "100Ah LiFePO4 Battery", system: "electrical", category: "Battery",
    brand: "Battle Born", model: "BB10012",
    dims: { l: 12.75, w: 6.875, h: 9 }, weightLb: 31, costUsd: 875,
    power: { voltage: "12V", watts: null, amps: 100, surgeWatts: null, idleWatts: null },
    capacity: { value: 100, unit: "Ah", kind: "Battery capacity" },
    mountingNotes: "Mount on a flat floor, strapped down. Group 27 footprint. Vents not required (LiFePO4).",
    sources: [{ label: "Battle Born spec page", url: "https://battlebornbatteries.com" }],
    confidence: "manufacturer", verified: true, tags: ["lithium", "house bank"], updatedAt: "2026-05-02",
  },
  {
    id: "el-mp-2000", name: "MultiPlus 12/2000/80 Inverter/Charger", system: "electrical", category: "Inverter/Charger",
    brand: "Victron", model: "PMP122200000",
    dims: { l: 14.6, w: 8.5, h: 6.1 }, weightLb: 23, costUsd: 760,
    power: { voltage: "12V", watts: 2000, amps: null, surgeWatts: 4000, idleWatts: 8 },
    capacity: { value: 2000, unit: "W", kind: "Continuous output" },
    mountingNotes: "Wall or floor mount near the battery to keep DC cable runs short. Leave clearance for the cooling fan.",
    sources: [{ label: "Victron datasheet", url: "https://www.victronenergy.com" }],
    confidence: "manufacturer", verified: true, tags: ["inverter", "shore charging"], updatedAt: "2026-05-02",
  },
  {
    id: "el-mppt-10050", name: "SmartSolar MPPT 100/50 Charge Controller", system: "electrical", category: "Charge Controller",
    brand: "Victron", model: "SCC110050210",
    dims: { l: 8.3, w: 5.9, h: 4.7 }, weightLb: 6, costUsd: 290,
    power: { voltage: "12V", watts: 700, amps: 50, surgeWatts: null, idleWatts: null },
    capacity: { value: 700, unit: "W", kind: "Max solar (12V)" },
    mountingNotes: "Vertical mount with clearance above/below for airflow. Short, fused run from controller to battery.",
    sources: [{ label: "Victron MPPT page", url: "https://www.victronenergy.com" }],
    confidence: "manufacturer", verified: true, tags: ["solar", "mppt", "bluetooth"], updatedAt: "2026-05-02",
  },
  {
    id: "el-rng-200", name: "200W Monocrystalline Solar Panel", system: "electrical", category: "Solar Panel",
    brand: "Renogy", model: "RNG-200D",
    dims: { l: 58.7, w: 26.4, h: 1.4 }, weightLb: 26.5, costUsd: 230,
    power: { voltage: "N/A", watts: 200, amps: null, surgeWatts: null, idleWatts: null },
    capacity: { value: 200, unit: "W", kind: "Rated output" },
    mountingNotes: "Roof-mount on Z-brackets or rail feet. Bed corner brackets in lap sealant; keep one cable gland for the run inside.",
    sources: [{ label: "Renogy product page", url: "https://www.renogy.com" }],
    confidence: "manufacturer", verified: false, tags: ["solar", "roof-mount"], updatedAt: "2026-04-18",
  },
  {
    id: "el-orion-30", name: "Orion-Tr Smart 12/12-30 DC-DC Charger", system: "electrical", category: "DC-DC Charger",
    brand: "Victron", model: "ORI121236120",
    dims: { l: 8.6, w: 4.6, h: 2.8 }, weightLb: 3.3, costUsd: 215,
    power: { voltage: "12V", watts: null, amps: 30, surgeWatts: null, idleWatts: null },
    capacity: { value: 30, unit: "Ah", kind: "Charge current" },
    mountingNotes: "Mount between starter and house battery to charge from the alternator while driving. Fuse both ends.",
    sources: [{ label: "Victron Orion-Tr", url: "https://www.victronenergy.com" }],
    confidence: "manufacturer", verified: true, tags: ["alternator charging", "b2b"], updatedAt: "2026-05-02",
  },
  {
    id: "el-bs-5026", name: "ST Blade Fuse Block (12 circuit)", system: "electrical", category: "Fuse Block",
    brand: "Blue Sea Systems", model: "5026",
    dims: { l: 7.1, w: 3.4, h: 1.4 }, weightLb: 0.7, costUsd: 55,
    power: { voltage: "12V", watts: null, amps: 100, surgeWatts: null, idleWatts: null },
    capacity: { value: 12, unit: "", kind: "Circuits" },
    mountingNotes: "Mount in an accessible spot with the cover on. Common negative bus included. Label every circuit.",
    sources: [{ label: "Blue Sea 5026", url: "https://www.bluesea.com" }],
    confidence: "verified", verified: true, tags: ["distribution", "fuses"], updatedAt: "2026-05-10",
  },
  {
    id: "el-aims-3000", name: "3000W Pure Sine Inverter", system: "electrical", category: "Inverter",
    brand: "AIMS Power", model: "PWRIX300012S",
    dims: { l: null, w: null, h: null }, weightLb: null, costUsd: 420,
    power: { voltage: "12V", watts: 3000, amps: null, surgeWatts: 6000, idleWatts: null },
    capacity: { value: 3000, unit: "W", kind: "Continuous output" },
    mountingNotes: "Needs very heavy DC cable (4/0) and a class-T fuse at the battery. Confirm exact dims/weight before buying.",
    sources: [],
    confidence: "unverified", verified: false, tags: ["inverter", "high-draw"], updatedAt: "2026-03-30",
  },
  {
    id: "el-lynx", name: "Lynx Distributor Busbar", system: "electrical", category: "Busbar",
    brand: "Victron", model: "LYN060102000",
    dims: { l: 8.5, w: 7.4, h: 3.5 }, weightLb: 3.5, costUsd: 190,
    power: { voltage: "12V", watts: null, amps: 1000, surgeWatts: null, idleWatts: null },
    capacity: { value: 1000, unit: "", kind: "Bus rating (A)" },
    mountingNotes: "Central positive/negative distribution with built-in fuse holders. Pairs with MultiPlus + MPPT.",
    sources: [{ label: "Victron Lynx", url: "https://www.victronenergy.com" }],
    confidence: "estimated", verified: false, tags: ["distribution", "busbar"], updatedAt: "2026-04-01",
  },

  // ---------------- PLUMBING ----------------
  {
    id: "pl-shurflo", name: "Revolution 4008 Water Pump", system: "plumbing", category: "Water Pump",
    brand: "SHURFLO", model: "4008-101-E65",
    dims: { l: 9.3, w: 5.0, h: 4.5 }, weightLb: 4.5, costUsd: 95,
    power: { voltage: "12V", watts: 90, amps: 7, surgeWatts: null, idleWatts: 0 },
    capacity: { value: 3, unit: "", kind: "Flow (GPM)" },
    mountingNotes: "Soft-mount on rubber feet to cut noise. Add an accumulator to stop cycling. Inline strainer on the inlet.",
    sources: [{ label: "SHURFLO 4008", url: "https://www.shurflo.com" }],
    confidence: "manufacturer", verified: true, tags: ["fresh water", "pump"], updatedAt: "2026-05-02",
  },
  {
    id: "pl-faucet", name: "Twist Combo Faucet", system: "plumbing", category: "Faucet",
    brand: "Whale", model: "RT2498",
    dims: { l: 4, w: 4, h: 11 }, weightLb: 1.2, costUsd: 75,
    power: null, capacity: null,
    mountingNotes: "Single-hole deck mount with a microswitch option to trigger the pump. Pull-out spray doubles as a shower.",
    sources: [{ label: "Whale faucets", url: "https://www.whalepumps.com" }],
    confidence: "estimated", verified: false, tags: ["fresh water", "galley"], updatedAt: "2026-04-12",
  },
  {
    id: "pl-shower", name: "Shower Pan 32 x 32", system: "plumbing", category: "Shower",
    brand: "Generic", model: "FRP-3232",
    dims: { l: 32, w: 32, h: 6 }, weightLb: 22, costUsd: 160,
    power: null, capacity: null,
    mountingNotes: "Wet-bay floor with a center or corner drain to the gray tank. Seal seams; slope toward the drain.",
    sources: [],
    confidence: "estimated", verified: false, tags: ["wet bath"], updatedAt: "2026-03-22",
  },
  {
    id: "pl-accum", name: "Accumulator Tank", system: "plumbing", category: "Accumulator",
    brand: "SEAFLO", model: "SFAT-125",
    dims: { l: 6.5, w: 6.5, h: 8 }, weightLb: 2, costUsd: 35,
    power: null, capacity: { value: 0.5, unit: "L", kind: "Air chamber" },
    mountingNotes: "Mount on the pressure side after the pump to smooth flow and stop rapid cycling. Pre-charge the air valve.",
    sources: [{ label: "SEAFLO accumulator", url: "https://www.seaflo.com" }],
    confidence: "unverified", verified: false, tags: ["fresh water"], updatedAt: "2026-02-28",
  },

  // ---------------- TANKS ----------------
  {
    id: "tk-fresh-21", name: "Fresh Water Tank 21 gal", system: "tank", category: "Fresh Tank",
    brand: "Generic", model: "FW-21",
    dims: { l: 30, w: 14, h: 12 }, weightLb: 18, costUsd: 150,
    power: null, capacity: { value: 21, unit: "gal", kind: "Potable water" },
    mountingNotes: "Strap low and central for balance — water is ~8.34 lb/gal (≈175 lb full). Fill port + vent + pickup.",
    sources: [],
    confidence: "estimated", verified: false, tags: ["fresh water"], updatedAt: "2026-03-15",
  },
  {
    id: "tk-gray-15", name: "Gray Water Tank 15 gal", system: "tank", category: "Gray Tank",
    brand: "Generic", model: "GW-15",
    dims: { l: 28, w: 12, h: 10 }, weightLb: 14, costUsd: 130,
    power: null, capacity: { value: 15, unit: "gal", kind: "Waste water" },
    mountingNotes: "Underslung or in a bay below the shower drain. Gravity-feed with a dump valve; vent to outside.",
    sources: [],
    confidence: "estimated", verified: false, tags: ["gray water"], updatedAt: "2026-03-15",
  },
  {
    id: "tk-lpg-11", name: "Propane Tank 11 lb (DOT)", system: "tank", category: "Propane",
    brand: "Worthington", model: "281149",
    dims: { l: 12.2, w: 12.2, h: 17.9 }, weightLb: 18.5, costUsd: 70,
    power: null, capacity: { value: 2.6, unit: "gal", kind: "Propane (≈11 lb)" },
    mountingNotes: "Upright, secured, in a vented/sealed locker that drains to outside. Regulator + leak detector required.",
    sources: [{ label: "Worthington cylinders", url: "https://www.worthingtonindustries.com" }],
    confidence: "manufacturer", verified: false, tags: ["propane", "fuel"], updatedAt: "2026-04-09",
  },
  {
    id: "tk-diesel-3", name: "Aux Diesel Tank 3 gal", system: "tank", category: "Diesel",
    brand: "Generic", model: "DSL-3",
    dims: { l: 14, w: 8, h: 8 }, weightLb: 5, costUsd: 60,
    power: null, capacity: { value: 3, unit: "gal", kind: "Heater fuel" },
    mountingNotes: "Feeds a diesel air heater. Mount the pickup standpipe; vent the tank. Keep fuel lines away from heat.",
    sources: [],
    confidence: "unverified", verified: false, tags: ["diesel", "heater fuel"], updatedAt: "2026-02-20",
  },

  // ---------------- HVAC ----------------
  {
    id: "hv-maxxfan", name: "MaxxFan Deluxe 7500K", system: "hvac", category: "Roof Fan",
    brand: "Maxxair", model: "00-07500K",
    dims: { l: 16, w: 16, h: 4.5 }, weightLb: 11, costUsd: 320,
    power: { voltage: "12V", watts: 60, amps: 5, surgeWatts: null, idleWatts: 0 },
    capacity: { value: 900, unit: "", kind: "Airflow (CFM)" },
    mountingNotes: "Standard 14x14 roof cutout. Rain shield lets it run in weather; remote + thermostat built in.",
    sources: [{ label: "Maxxair fans", url: "https://www.maxxair.com" }],
    confidence: "manufacturer", verified: true, tags: ["ventilation", "roof"], updatedAt: "2026-05-02",
  },
  {
    id: "hv-penguin", name: "Penguin II Rooftop AC 13500 BTU", system: "hvac", category: "Air Conditioner",
    brand: "Dometic", model: "640315CXX1J0",
    dims: { l: 29, w: 28, h: 9.8 }, weightLb: 77, costUsd: 1150,
    power: { voltage: "120V", watts: 1450, amps: 13, surgeWatts: 2900, idleWatts: null },
    capacity: { value: 13500, unit: "BTU", kind: "Cooling" },
    mountingNotes: "Heavy roof load — confirm payload and roof structure. Needs a large inverter or shore power to run.",
    sources: [{ label: "Dometic Penguin II", url: "https://www.dometic.com" }],
    confidence: "manufacturer", verified: false, tags: ["cooling", "roof", "high-draw"], updatedAt: "2026-04-25",
  },
  {
    id: "hv-espar", name: "Airtronic B4 Diesel Heater", system: "hvac", category: "Heater",
    brand: "Espar", model: "B4L",
    dims: { l: 12, w: 4.7, h: 5.1 }, weightLb: 6, costUsd: 1300,
    power: { voltage: "12V", watts: 30, amps: 2.5, surgeWatts: 110, idleWatts: null },
    capacity: { value: 13648, unit: "BTU", kind: "Heat output (≈4kW)" },
    mountingNotes: "Mount under floor or in a bay with intake/exhaust to outside. Draws from main or aux diesel tank.",
    sources: [{ label: "Espar heaters", url: "https://www.espar.com" }],
    confidence: "estimated", verified: false, tags: ["heat", "diesel"], updatedAt: "2026-04-03",
  },
  {
    id: "hv-propex", name: "HS2000 Propane Heater", system: "hvac", category: "Heater",
    brand: "Propex", model: "HS2000",
    dims: { l: 11, w: 6.7, h: 6.3 }, weightLb: 9, costUsd: 650,
    power: { voltage: "12V", watts: 18, amps: 1.5, surgeWatts: null, idleWatts: null },
    capacity: { value: 6824, unit: "BTU", kind: "Heat output (≈2kW)" },
    mountingNotes: "Sealed combustion — intake/exhaust to outside. Runs off the propane system; ducted warm air inside.",
    sources: [{ label: "Propex heaters", url: "https://www.propexheating.com" }],
    confidence: "manufacturer", verified: false, tags: ["heat", "propane"], updatedAt: "2026-04-03",
  },

  // ---------------- ROOF ----------------
  {
    id: "rf-rack", name: "Modular Roof Rack (per ft)", system: "roof", category: "Roof Rack",
    brand: "Generic", model: "RR-MOD",
    dims: { l: 12, w: 50, h: 4 }, weightLb: 9, costUsd: 110,
    power: null, capacity: { value: 300, unit: "", kind: "Static load (lb)" },
    mountingNotes: "Bolts to factory roof mounts or fender washers w/ backing plates + sealant. Spreads solar + deck loads.",
    sources: [],
    confidence: "estimated", verified: false, tags: ["roof", "structure"], updatedAt: "2026-03-08",
  },
  {
    id: "rf-gland", name: "Cable Entry Gland (triple)", system: "roof", category: "Cable Gland",
    brand: "Scanstrut", model: "DS-MULTI",
    dims: { l: 3.3, w: 3.3, h: 1.4 }, weightLb: 0.3, costUsd: 45,
    power: null, capacity: { value: 3, unit: "", kind: "Cable ports" },
    mountingNotes: "Weatherproof roof penetration for solar/antenna cables. Bed in lap sealant; route to the controller.",
    sources: [{ label: "Scanstrut glands", url: "https://www.scanstrut.com" }],
    confidence: "unverified", verified: false, tags: ["roof", "weatherproofing"], updatedAt: "2026-02-15",
  },

  // ---------------- APPLIANCES ----------------
  {
    id: "ap-cfx3-45", name: "CFX3 45 Fridge/Freezer", system: "appliance", category: "Refrigerator",
    brand: "Dometic", model: "CFX3 45",
    dims: { l: 28.1, w: 18.5, h: 16.1 }, weightLb: 41, costUsd: 900,
    power: { voltage: "12V", watts: 45, amps: 3.7, surgeWatts: null, idleWatts: null },
    capacity: { value: 1.6, unit: "cu_ft", kind: "Interior (46 L)" },
    mountingNotes: "Allow airflow around the compressor side. Slide mount for lid access. ~30–50 Ah/day depending on temp.",
    sources: [{ label: "Dometic CFX3", url: "https://www.dometic.com" }],
    confidence: "manufacturer", verified: true, tags: ["fridge", "12v"], updatedAt: "2026-05-02",
  },
  {
    id: "ap-induction", name: "2-Burner Induction Cooktop", system: "appliance", category: "Cooktop",
    brand: "Generic", model: "IND-2B",
    dims: { l: 23, w: 14, h: 2.5 }, weightLb: 12, costUsd: 180,
    power: { voltage: "120V", watts: 1800, amps: 15, surgeWatts: null, idleWatts: 1 },
    capacity: { value: 1800, unit: "W", kind: "Peak draw" },
    mountingNotes: "High AC draw — size the inverter for it or run on shore power. Needs clearance and ventilation above.",
    sources: [],
    confidence: "estimated", verified: false, tags: ["cooking", "high-draw"], updatedAt: "2026-03-19",
  },
  {
    id: "ap-natureshead", name: "Composting Toilet", system: "appliance", category: "Toilet",
    brand: "Nature's Head", model: "NH-STD",
    dims: { l: 19, w: 20.5, h: 20 }, weightLb: 28, costUsd: 1030,
    power: { voltage: "12V", watts: 2, amps: 0.15, surgeWatts: null, idleWatts: null },
    capacity: { value: 2, unit: "", kind: "Vent fan (W)" },
    mountingNotes: "Bolt to floor; vent the fan to outside. Separates liquids/solids — no black tank or plumbing needed.",
    sources: [{ label: "Nature's Head", url: "https://natureshead.net" }],
    confidence: "manufacturer", verified: false, tags: ["toilet", "no plumbing"], updatedAt: "2026-04-21",
  },

  // ---------------- CABINETRY ----------------
  {
    id: "cb-upper", name: "Upper Galley Cabinet (custom)", system: "cabinetry", category: "Overhead Cabinet",
    brand: "Custom", model: "UPPER-36",
    dims: { l: 36, w: 12, h: 14 }, weightLb: 40, costUsd: 350,
    power: null, capacity: { value: 3, unit: "cu_ft", kind: "Storage" },
    mountingNotes: 'Lag into wall ribs or unistrut backing — never just into sheet metal. 1/2"–3/4" birch ply with doors.',
    sources: [],
    confidence: "estimated", verified: false, tags: ["storage", "plywood"], updatedAt: "2026-03-11",
  },
  {
    id: "cb-bed", name: "Bed Platform Frame (custom)", system: "cabinetry", category: "Bed Frame",
    brand: "Custom", model: "BED-PLAT",
    dims: { l: 74, w: 54, h: 14 }, weightLb: 120, costUsd: 350,
    power: null, capacity: { value: 400, unit: "", kind: "Rated load (lb)" },
    mountingNotes: '2x2 frame with 3/4" deck and slats; ties into wall studs. Garage storage underneath.',
    sources: [],
    confidence: "estimated", verified: false, tags: ["sleeping", "plywood"], updatedAt: "2026-03-11",
  },
  {
    id: "cb-galley", name: "Galley Base Cabinet (custom)", system: "cabinetry", category: "Base Cabinet",
    brand: "Custom", model: "GALLEY-40",
    dims: { l: 40, w: 24, h: 36 }, weightLb: 110, costUsd: 600,
    power: null, capacity: { value: 8, unit: "cu_ft", kind: "Storage" },
    mountingNotes: "Birch ply carcass, butcher-block top, drawer slides, sink cutout. Bolt to floor + wall.",
    sources: [],
    confidence: "estimated", verified: false, tags: ["kitchen", "plywood"], updatedAt: "2026-03-11",
  },

  // ---------------- MATERIALS ----------------
  {
    id: "mt-havelock", name: "Havelock Wool Insulation (bag)", system: "material", category: "Insulation",
    brand: "Havelock Wool", model: "HW-BATT",
    dims: { l: null, w: null, h: null }, weightLb: 18, costUsd: 110,
    power: null, capacity: { value: 30, unit: "sq_ft", kind: "Coverage (≈2in)" },
    mountingNotes: "Friction-fit into cavities; breathable, manages moisture. R≈3.4/in. No vapor barrier needed.",
    sources: [{ label: "Havelock Wool", url: "https://havelockwool.com" }],
    confidence: "estimated", verified: false, tags: ["insulation", "wool"], updatedAt: "2026-04-07",
  },
  {
    id: "mt-thinsulate", name: "3M Thinsulate SM600L (roll)", system: "material", category: "Insulation",
    brand: "3M", model: "SM600L",
    dims: { l: null, w: 60, h: null }, weightLb: 12, costUsd: 220,
    power: null, capacity: { value: 50, unit: "sq_ft", kind: "Coverage (per roll)" },
    mountingNotes: "Spray-glue to walls/ceiling. Hydrophobic, fills irregular cavities. R≈5.2 at 1.6in loft.",
    sources: [{ label: "3M Thinsulate", url: "https://www.3m.com" }],
    confidence: "manufacturer", verified: false, tags: ["insulation", "synthetic"], updatedAt: "2026-04-07",
  },
];
